"""Rename Problem.problemtype to Problem.problemtypeid

Revision ID: 8b461494fd5b
Revises: 
Create Date: 2017-09-04 15:12:04.263127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b461494fd5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('problemtypeid', sa.Integer(), nullable=True))
    op.drop_constraint('problem_problemtype_fkey', 'problem', type_='foreignkey')
    op.create_foreign_key(None, 'problem', 'problem_type', ['problemtypeid'], ['id'])
    op.drop_column('problem', 'problemtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('problemtype', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.create_foreign_key('problem_problemtype_fkey', 'problem', 'problem_type', ['problemtype'], ['id'])
    op.drop_column('problem', 'problemtypeid')
    # ### end Alembic commands ###
